# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb006c595c9e4aeee03bd4ea9c6e6744dcdf09cfdcf745d74e26b3983f1680fe53688b0924f242b714f6d107a1fce4c4fd6242bdb8eda3537da17136d0b8e290

test:
  secret_key_base: 86f733ef287fb8a70a3f2b55ef629b89db37ea0b3fa411adaff426f19b5e21fcc72f9cb04113bdb9a65c2c44ddc5c2ae87b8cbde6df579371ffab5bfa52066d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
